### ISSUE TITLE
Expose pthread bindings?

### ISSUE THREAD

**Issue by facundominguez** [rrnewton/thread-local-storage#13]
In a [PR](https://github.com/tweag/inline-java/pull/86) for the `jni` package, we have a module [Control.Concurrent.PThread](https://github.com/tweag/inline-java/blob/7f573680cbda41c537e6cb40d71c0fe2586bad2d/jni/src/Control/Concurrent/PThread.hsc) that we would like to move to another package. Is this something you would be interested in having in `thread-local-storage`?

`thread-local-storage` has some of the same bindings, but they are considered internal, and we would need them as a public and stable low-level interface.

The other alternative would be to start a package `pthread` with them.

**Comment by RyanGlScott** [comment]
My gut reaction is that this would be better suited to a separate package. I'd prefer to keep this package dedicated to the high-level (or at least medium-level) abstraction it offers and not complicate the public API with C bindings.

There's also the issue that the `pthread` bindings in `thread-local-storage` and `jni` are ever so slightly different—for example, contrast the type signatures of `pthread_key_create` in the two packages. Perhaps this difference could be resolved, but not without some refactoring, I'd imagine.

**Comment by facundominguez** [comment]
Thanks for taking a look. Will pursue a package `pthread` then.
