### ISSUE TITLE
use forkOS instead of forkOn for benchmarks

### ISSUE THREAD

**Issue by wangbj** [rrnewton/thread-local-storage#14]
forkOn creates unbounded thread, it would cause error when run benchmarks:

```haskell
   fail "thread-local-storage: PThread.getTLS used from an unbound thread."
```

**Comment by RyanGlScott** [comment]
Actually, never mind. It turns out that the changes from https://github.com/rrnewton/thread-local-storage/pull/10 aren't on Hackage yet, so this can wait, I suppose.

**Comment by wangbj** [comment]
Sure, sorry wasn’t aware there’s an issue already
