### ISSUE TITLE
Submit to Stackage

### ISSUE THREAD

**Issue by mboes** [rrnewton/thread-local-storage#5]
This package has found good use in inline-java. Which we'll be submitting to Stackage once 8.0.2 comes out and Stackage switches to it (8.0.1 has a debilitating bug that we can't work around). A prereq to that is including all  dependencies in Stackage too.

See the "Authors" section of the Stackage home page.

**Comment by RyanGlScott** [comment]
Done in https://github.com/fpco/stackage/pull/2226.
